[package]
name = "my-2nd-yew-app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-router = "0.16"
stdweb = "0.4.7"
rand = "0.6.5"
wasm-logger = "0.2.0"
log = "0.4.6"
gloo-events = "0.1"
web-sys = { version = "0.3.4", features = ["Document", "Window"]}
wasm-bindgen = "0.2.79"

[patch.crates-io]
stdweb = { git = 'https://github.com/arturoc/stdweb.git' }